config/routes.rb
Rails.application.routes.draw do
  resources :logentries

resources :wines do
  resources :logentries
  get 'page/:page', :action => :index, :on => :collection
end
root 'wines#index'
end

app/models/logentry.rb
class Logentry < ActiveRecord::Base
  belongs_to :wine

RATINGS = 1..5

validates :name, :location, :rating,  :comments, :tasted_on, presence: true
validates :rating, inclusion: { in: RATINGS, message: "must be from #{RATINGS.first} to #{RATINGS.last}" }
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  VARIETALS = [ 'Burgundy', 'Chablis', 'Chianti', 'Chardonay', 'Reisling', 'Rose', 'Zinfendel']
  validates :name, :year, :country, :varietal, :winery, presence: true
  validates :year, numericality: {only_integer: true, greater_than_or_equal_to: 1500}
  validates :varietal,
    :inclusion => { :in => VARIETALS,
    :message => "%{value} is not a valid varietal."}
    has_many :logentries, dependent: :destroy

def average_rating
  logentries.average(:rating)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/logentries_controller.rb
class LogentriesController < ApplicationController
  before_action :set_wine

def index
  @logentries = @wine.logentries.order('created_at desc')
end

def new
  @logentry = @wine.logentries.new
end

def create
  @logentry = @wine.logentries.new(logentry_params)
  if @logentry.save
    redirect_to wine_logentries_path(@wine), notice: 'Log entry saved!'
  else
render :new
  end
end


private

def set_wine
  @wine = Wine.find(params[:wine_id])
end

def logentry_params
  params.require(:logentry).permit(:name, :rating, :location, :comments, :tasted_on)
end


end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def index
    @wines = Wine.order(:name).page(params[:page])
  end

  def show
    @wine = Wine.find(params[:id])
  end

def new
  @wine = Wine.new
end

def create
  #@wine = Wine.new(wine_params)
  #@wine.save
  #redirect_to @wine

@wine = Wine.new(wine_params)
if @wine.save
  redirect_to @wine, notice: "#{@wine.name} was created!"
else
  render :new
end
end

def edit
  @wine = Wine.find(params[:id])
end

def update
  @wine = Wine.find(params[:id])
  #@wine.update(wine_params)
  #redirect_to @wine

if @wine.update(wine_params)
  redirect_to @wine, notice: "#{@wine.name} was updated!"
else
  render :edit
end

end

private
def wine_params
  params.require(:wine).permit(:name, :year, :winery, :country, :varietal)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logentries_helper.rb
module LogentriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end

  def format_average_rating(wine)
    average = wine.average_rating
    if average
      pluralize(number_with_precision(average, precision: 1), 'star')
    else
      'No ratings.'
    end
  end

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Wine Review', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Navigation</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Wines', wines_path %>
      </p>
      <p>
        <%= link_to 'New Wine', new_wine_path %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wine Review<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/logentries/_form.html.erb
<%= form_for( [ @wine, @logentry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @logentry %>

  <div class="formLabel"><%= f.label :name %></div>
  <div class="formField"><%= f.text_field :name, autofocus: true, placeholder: 'Name' %></div>
  <div class="clearAll"></div>
 <div class="formLabel"> <%= f.label :ratings %></div>
   <div class="formField">
  <% Logentry::RATINGS.each do |ratings| %>
    <%= f.radio_button :rating, ratings %> <%= ratings %>
  <% end %> </div>
   <div class="clearAll"></div>
  <div class="formLabel"><%= f.label :comments %></div>
   <div class="formField"><%= f.text_area :comments %></div>
   <div class="clearAll"></div>
  <div class="formLabel"><%= f.label :location %>  </div>
     <div class="formField"><%= f.text_area :location %></div>
   <div class="clearAll"></div>

<div class="formLabel"><%= f.label :tasted_on %>  </div>

<div class="formField">
<%= f.date_select :tasted_on %>
</div>
 <div class="clearAll"></div>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_logentries_path(@wine), id: 'cancel_logentry' %>
  </p>
<% end %>

app/views/logentries/index.html.erb
<header>Log Entries for <%= link_to(@wine.name, @wine) %></header>
<ol id="logentries">
  <% @logentries.each do |logentry| %>
    <li>
      <span class="logentry"><%= pluralize(logentry.rating, 'star') %></span>
      <span class="user">by <%= logentry.name %> </span>
      <span class="date">
        <%= time_ago_in_words(logentry.tasted_on) %> ago
      </span>
      <p>
        &quot;<%= logentry.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>

<%= link_to 'Log a new entry', new_wine_logentry_path(@wine),
        remote: true,
        data: { 'update-target' => 'logentry_form_container' },
        class: 'btn btn-primary' %>

<div id="logentry_form_container"></div>

app/views/logentries/new.html.erb
<h1>Log an entry for <%= @wine.name %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
<%= render 'shared/validation_errors', object: @wine %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br /><br />
  <%= f.label :year %> <%= f.text_field :year %><br /><br />
  <%= f.label :winery %> <%= f.text_field :winery %><br /><br />
  <%= f.label :country %> <%= f.text_field :country %><br /><br />

  <%= f.label :varietal %><%= f.select :varietal, Wine::VARIETALS, { prompt: "Pick one" } %><br /><br />

  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wines_path %>
  </p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines for Sale</h1>
<%= page_entries_info @wines %>
<ol>
<% @wines.each do |wine| %>
  <li><%= link_to(wine.name, wine) %> is a <%= wine.varietal %> from <%= wine.winery %></li>
<% end %>
</ol>
<%= paginate @wines %>

app/views/wines/new.html.erb
<h1>Enter New Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<% content_for :name, @wine.name %>
<article class="wine">
<header>
<h2><%= @wine.name %></h2>
</header>

<p><label>Year:</label> <%= @wine.year %></p>
<p><label>Winery:</label> <%= @wine.winery %></p>
<p><label>Country:</label> <%= @wine.country %></p>
<p><label>Varietal:</label> <%= @wine.varietal %></p>

<p>
  Read all
  <%= link_to pluralize(@wine.logentries.size, 'entry'), wine_logentries_path(@wine) %>
  <p><label>Average Rating:</label> <%= format_average_rating(@wine) %></p>
</p>

</article>

<%= link_to 'All Wines', wines_path %> | <%= link_to 'Edit', edit_wine_path(@wine) %>